
name: Ruby CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        # would be nice to build for other 3.x as required but overkill for poc
    - name: Install dependencies
      run: bundle install
    - name: Rubocop on the beat
      run: ./bin/rubocop
    - name: Bundler Audit
      run: ./bin/bundler-audit update && ./bin/bundler-audit check
    - name: Brakeman scan
      run: ./bin/brakeman -o brakeman-report.md && cat brakeman-report.md
    - name: Prep Test DB
      run: RAILS_ENV=test devise_jwt_secret_key=c7501bb520d28b3942e802d39f688c025e05efafa293bc9d40bbfb9b063a7ef7d52bd81c9a8f825cf3290e3ed02bdea3e52cf30540868195ea1c8333fb855a09 ./bin/rails db:test:prepare
    - name: Run tests
      run: bundle exec rake
