

name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.4'
        # would be nice to build for 3.x and others as required but overkill for poc
    - name: Install dependencies
      run: bundle install
    - name: Rubocop on the beat
      run: ./bin/rubocop
    - name: Bundler Audit
      run: ./bin/bundler-audit update && ./bin/bundler-audit check
    - name: Brakeman scan
      run: ./bin/brakeman -o brakeman-report.md && cat brakeman-report.md
    - name: Run tests
      run: bundle exec rake
