

name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        # would be nice to build for other 3.x as required but overkill for poc
    - name: Install dependencies
      run: bundle install
    - name: Rubocop on the beat
      run: ./bin/rubocop
    - name: Bundler Audit
      run: ./bin/bundler-audit update && ./bin/bundler-audit check
    - name: Brakeman scan
      run: ./bin/brakeman -o brakeman-report.md && cat brakeman-report.md
    - name: Run tests
      run: RAILS_ENV=test ./bin/rails db:test:prepare
    - name: Run tests
      run: bundle exec rake
